export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];


export const languageCountryList = [
  { label: "Afrikaans (South Africa)", language: "Afrikaans", countryCode: "ZA" },
  { label: "Amharic (Ethiopia)", language: "Amharic", countryCode: "ET" },
  { label: "Arabic (Saudi Arabia)", language: "Arabic", countryCode: "SA" },
  { label: "Azerbaijani (Azerbaijan)", language: "Azerbaijani", countryCode: "AZ" },
  { label: "Belorussian (Belarus)", language: "Belorussian", countryCode: "BY" },
  { label: "Bulgarian (Bulgaria)", language: "Bulgarian", countryCode: "BG" },
  { label: "Bengali (Bangladesh)", language: "Bengali", countryCode: "BD" },
  { label: "Breton (France)", language: "Breton", countryCode: "FR" },
  { label: "Bosnian (Bosnia & Herzegovina)", language: "Bosnian", countryCode: "BA" },
  { label: "Catalan (Spain)", language: "Catalan", countryCode: "ES" },
  { label: "Czech (Czech Republic)", language: "Czech", countryCode: "CZ" },
  { label: "Cymraeg (United Kingdom)", language: "Cymraeg", countryCode: "GB" },
  { label: "Danish (Denmark)", language: "Danish", countryCode: "DK" },
  { label: "German (Germany)", language: "German", countryCode: "DE" },
  { label: "Dhivehi (Maldives)", language: "Dhivehi", countryCode: "MV" },
  { label: "English (United States)", language: "English", countryCode: "US" },
  { label: "Spanish (Spain)", language: "Spanish", countryCode: "ES" },
  { label: "Estonian (Estonia)", language: "Estonian", countryCode: "EE" },
  { label: "Basque (Spain)", language: "Basque", countryCode: "ES" },
  { label: "Persian (Iran)", language: "Persian", countryCode: "IR" },
  { label: "Finnish (Finland)", language: "Finnish", countryCode: "FI" },
  { label: "French (France)", language: "French", countryCode: "FR" },
  { label: "Irish (Ireland)", language: "Irish", countryCode: "IE" },
  { label: "Galician (Spain)", language: "Galician", countryCode: "ES" },
  { label: "Greek (Greece)", language: "Greek", countryCode: "GR" },
  { label: "Hausa (Nigeria)", language: "Hausa", countryCode: "NG" },
  { label: "Hebrew (Israel)", language: "Hebrew", countryCode: "IL" },
  { label: "Hindi (India)", language: "Hindi", countryCode: "IN" },
  { label: "Croatian (Croatia)", language: "Croatian", countryCode: "HR" },
  { label: "Hungarian (Hungary)", language: "Hungarian", countryCode: "HU" },
  { label: "Armenian (Armenia)", language: "Armenian", countryCode: "AM" },
  { label: "Icelandic (Iceland)", language: "Icelandic", countryCode: "IS" },
  { label: "Italian (Italy)", language: "Italian", countryCode: "IT" },
  { label: "Indonesian (Indonesia)", language: "Indonesian", countryCode: "ID" },
  { label: "Japanese (Japan)", language: "Japanese", countryCode: "JP" },
  { label: "Georgian (Georgia)", language: "Georgian", countryCode: "GE" },
  { label: "Kazakh (Kazakhstan)", language: "Kazakh", countryCode: "KZ" },
  { label: "Khmer (Cambodia)", language: "Khmer", countryCode: "KH" },
  { label: "Korean (South Korea)", language: "Korean", countryCode: "KR" },
  { label: "Kurdish (Iraq)", language: "Kurdish", countryCode: "IQ" },
  { label: "Kyrgyz (Kyrgyzstan)", language: "Kyrgyz", countryCode: "KG" },
  { label: "Lithuanian (Lithuania)", language: "Lithuanian", countryCode: "LT" },
  { label: "Latvian (Latvia)", language: "Latvian", countryCode: "LV" },
  { label: "Macedonian (North Macedonia)", language: "Macedonian", countryCode: "MK" },
  { label: "Malayalam (India)", language: "Malayalam", countryCode: "IN" },
  { label: "Mongolian (Mongolia)", language: "Mongolian", countryCode: "MN" },
  { label: "Marathi (India)", language: "Marathi", countryCode: "IN" },
  { label: "Malay (Malaysia)", language: "Malay", countryCode: "MY" },
  { label: "Maltese (Malta)", language: "Maltese", countryCode: "MT" },
  { label: "Norwegian Bokmål (Norway)", language: "Norwegian Bokmål", countryCode: "NO" },
  { label: "Dutch (Netherlands)", language: "Dutch", countryCode: "NL" },
  { label: "Norwegian Nynorsk (Norway)", language: "Norwegian Nynorsk", countryCode: "NO" },
  { label: "Norwegian (Norway)", language: "Norwegian", countryCode: "NO" },
  { label: "Polish (Poland)", language: "Polish", countryCode: "PL" },
  { label: "Pashto (Afghanistan)", language: "Pashto", countryCode: "AF" },
  { label: "Portuguese (Portugal)", language: "Portuguese", countryCode: "PT" },
  { label: "Romanian (Romania)", language: "Romanian", countryCode: "RO" },
  { label: "Russian (Russia)", language: "Russian", countryCode: "RU" },
  { label: "Sindhi (Pakistan)", language: "Sindhi", countryCode: "PK" },
  { label: "Slovak (Slovakia)", language: "Slovak", countryCode: "SK" },
  { label: "Slovene (Slovenia)", language: "Slovene", countryCode: "SI" },
  { label: "Somali (Somalia)", language: "Somali", countryCode: "SO" },
  { label: "Albanian (Albania)", language: "Albanian", countryCode: "AL" },
  { label: "Serbian (Serbia)", language: "Serbian", countryCode: "RS" },
  { label: "Swedish (Sweden)", language: "Swedish", countryCode: "SE" },
  { label: "Swahili (Kenya)", language: "Swahili", countryCode: "KE" },
  { label: "Tamil (India)", language: "Tamil", countryCode: "IN" },
  { label: "Tajik (Tajikistan)", language: "Tajik", countryCode: "TJ" },
  { label: "Thai (Thailand)", language: "Thai", countryCode: "TH" },
  { label: "Turkmen (Turkmenistan)", language: "Turkmen", countryCode: "TM" },
  { label: "Turkish (Turkey)", language: "Turkish", countryCode: "TR" },
  { label: "Tatar (Russia)", language: "Tatar", countryCode: "RU" },
  { label: "Uyghur (China)", language: "Uyghur", countryCode: "CN" },
  { label: "Ukrainian (Ukraine)", language: "Ukrainian", countryCode: "UA" },
  { label: "Urdu (Pakistan)", language: "Urdu", countryCode: "PK" },
  { label: "Uzbek (Uzbekistan)", language: "Uzbek", countryCode: "UZ" },
  { label: "Chinese (China)", language: "Chinese", countryCode: "CN" },
  { label: "Vietnamese (Vietnam)", language: "Vietnamese", countryCode: "VN" }
];